-

diff --git a/.github/workflows/azure.yml b/.github/workflows/azure.yml
--- a/.github/workflows/azure.yml
+++ b/.github/workflows/azure.yml
@@ -20,32 +20,42 @@ jobs:
         run: cp clss_deployment_package.zip ship/
       - name: Print files in ship directory
         run: ls -la ship
+      - name: Print current working directory after copying
+        run: pwd
+      - name: Check if clss_deployment_package.zip exists
+        run: |
+          if [ ! -f ship/clss_deployment_package.zip ]; then
+            echo "clss_deployment_package.zip not found in ship directory."
+            exit 1
+          else
+            echo "clss_deployment_package.zip found."
+          fi
       - name: Unzip deployment package
         run: unzip -q /ship/clss_deployment_package.zip -d /ship/clss_deployment_package
-      - name: Update config.json with secrets
-        run: |
-          sed -i "s|\"portalUrl\": \"${{ secrets.AGOL_PORTAL_URL }}\"|g" clss_deployment_package/config.json
-          sed -i "s|\"username\": \"${{ secrets.AGOL_USERNAME }}\"|g" clss_deployment_package/config.json
-          sed -i "s|\"password\": \"${{ secrets.AGOL_PASSWORD }}\"|g" clss_deployment_package/config.json
-          sed -i "s|\"appUrl\": \"${{ secrets.AZURE_WEBSITE_URL }}\"|g" clss_deployment_package/config.json
-        working-directory: ship/clss_deployment_package
-      - name: Run node script, deploy.js to create app code
-        run: |
-          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
-            node -e "require('./deploy.js').executeDeployment()" 
-          fi
+      # - name: Update config.json with secrets
+      #   run: |
+      #     sed -i "s|\"portalUrl\": \"${{ secrets.AGOL_PORTAL_URL }}\"|g" clss_deployment_package/config.json
+      #     sed -i "s|\"username\": \"${{ secrets.AGOL_USERNAME }}\"|g" clss_deployment_package/config.json
+      #     sed -i "s|\"password\": \"${{ secrets.AGOL_PASSWORD }}\"|g" clss_deployment_package/config.json
+      #     sed -i "s|\"appUrl\": \"${{ secrets.AZURE_WEBSITE_URL }}\"|g" clss_deployment_package/config.json
+      #   working-directory: ship/clss_deployment_package
+      # - name: Run node script, deploy.js to create app code
+      #   run: |
+      #     if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
+      #       node -e "require('./deploy.js').executeDeployment()"
+      #     fi
 
-      - name: Deploy app to azure static web app
-        uses: Azure/static-web-apps-deploy@v1
-        with:
-          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_DEPLOYMENT_TEST_SITE }}
-          repo_token: ${{ secrets.GITHUB_TOKEN }}
-          action: "upload"
-          app_location: "/clss_deployment_package/app" # App source code path
-          api_location: "" # Api source code path - optional
-          output_location: "/clss_deployment_package/app" # Built app content directory - optional
-          production_branch: "main"
-          skip_app_build: true
-          skip_api_build: true
+      # - name: Deploy app to azure static web app
+      #   uses: Azure/static-web-apps-deploy@v1
+      #   with:
+      #     azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_DEPLOYMENT_TEST_SITE }}
+      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
+      #     action: "upload"
+      #     app_location: "/clss_deployment_package/app" # App source code path
+      #     api_location: "" # Api source code path - optional
+      #     output_location: "/clss_deployment_package/app" # Built app content directory - optional
+      #     production_branch: "main"
+      #     skip_app_build: true
+      #     skip_api_build: true
 
-          ###### End of Repository/Build Configurations  ######
+      ###### End of Repository/Build Configurations  ######
