-

diff --git a/.github/workflows/azure.yml b/.github/workflows/azure.yml
--- a/.github/workflows/azure.yml
+++ b/.github/workflows/azure.yml
@@ -38,10 +38,23 @@ jobs:
           ls -lh clss_deployment_package.tar.gz
         working-directory: ship
 
+      - name: Check if tar command is available
+        run: |
+          if ! command -v tar &> /dev/null; then
+            echo "tar command not found"
+            exit 1
+          fi
+
+      - name: Check file before extraction
+        run: |
+          echo "Contents of clss_deployment_package.tar.gz before extraction:"
+          tar -tzf clss_deployment_package.tar.gz
+        working-directory: ship
+
       - name: Extract .tar.gz file
         run: |
           mkdir extracted
-          tar -xf clss_deployment_package.tar.gz -C extracted
+          tar -xzf clss_deployment_package.tar.gz -C extracted
         working-directory: ship
 
       - name: Print files in ship directory
